development:
  adapter: any_cable
  # adapter: async

test:
  adapter: async

production:
  adapter: any_cable
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: ASD-Backend_production
